# Generated by Django 3.2.5 on 2021-07-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.BigIntegerField(verbose_name="ID da mensagem")),
                ("group", models.CharField(max_length=255, verbose_name="Grupo")),
                ("sender", models.CharField(max_length=255, verbose_name="remetente")),
                ("sent_at", models.DateTimeField(verbose_name="enviado em")),
                ("message", models.TextField(verbose_name="mensagem")),
                ("video", models.JSONField(default=dict, verbose_name="vídeo")),
                ("audio", models.JSONField(default=dict, verbose_name="áudio")),
                ("document", models.JSONField(default=dict, verbose_name="documento")),
                ("photo", models.JSONField(default=dict, verbose_name="imagem")),
                (
                    "forwarded",
                    models.BooleanField(default=False, verbose_name="encaminhada"),
                ),
            ],
            options={
                "verbose_name": "mensagem",
                "verbose_name_plural": "mensagens",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sent_at"], name="core_messag_sent_at_7d3b57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["group"], name="core_messag_group_54e083_idx"),
        ),
    ]
