# Generated by Django 3.2.5 on 2021-07-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_creates_message_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.BigIntegerField(unique=True, verbose_name='ID da mensagem'),
        ),
    ]
