# Generated by Django 3.2.5 on 2021-07-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_message_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='grupo')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
        ),
    ]
