# Generated by Django 3.2.6 on 2021-08-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['id'], 'verbose_name': 'grupo', 'verbose_name_plural': 'grupos'},
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.BigIntegerField(verbose_name='ID da mensagem'),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('message_id', 'group')},
        ),
    ]
