# Generated by Django 3.2.6 on 2021-09-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210823_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID do usuário')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='Usuário')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Sobrenome')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Telefone')),
                ('photo', models.JSONField(default=dict, null=True, verbose_name='Foto de perfil')),
                ('fake', models.BooleanField(default=False, verbose_name='Falso')),
                ('deleted', models.BooleanField(default=False, verbose_name='Excluído')),
                ('verified', models.BooleanField(default=False, verbose_name='Verificado')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['user_id'], name='core_telegr_user_id_93fecf_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['username'], name='core_telegr_usernam_b0aeb3_idx'),
        ),
    ]
