# Generated by Django 3.2.7 on 2021-09-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_creates_telegramuser_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='photo_url',
            field=models.CharField(max_length=1024, null=True, verbose_name='URL da imagem'),
        ),
    ]
