# Generated by Django 3.2.7 on 2021-09-09 20:47

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_message_audio_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="message",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="core_messag_search__38844b_gin"
            ),
        ),
    ]
