# Generated by Django 3.2.7 on 2021-09-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_creates_search_vector_field_in_message_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='video_url',
            field=models.CharField(max_length=1024, null=True, verbose_name='URL do vídeo'),
        ),
    ]
