# Generated by Django 3.2.7 on 2022-02-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_message_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users_count',
            field=models.IntegerField(null=True, verbose_name='usuários'),
        ),
    ]
