# Generated by Django 3.2.7 on 2022-02-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_message_core_messag_sender_1fed39_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(verbose_name='Data de geração')),
            ],
            options={
                'verbose_name': 'relatório',
                'verbose_name_plural': 'relatórios',
            },
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
    ]
