# Generated by Django 3.2.7 on 2022-02-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220212_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_data',
            field=models.JSONField(default=dict, null=True, verbose_name='Dados'),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID do relatório'),
        ),
    ]
