# Generated by Django 3.2.7 on 2022-03-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220223_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
