# Generated by Django 3.2.7 on 2022-10-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_id',
            field=models.BigIntegerField(null=True, verbose_name='ID da mídia'),
        ),
    ]
