# Generated by Django 3.2.7 on 2022-10-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_message_core_messag_media_i_ce20f4_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'mensagem', 'verbose_name_plural': 'mensagens'},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='core_messag_sent_at_7d3b57_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-sent_at'], name='core_messag_sent_at_b6042b_idx'),
        ),
    ]
