version: '3'

services:
  telegram_scrapper:
    image: python:3.9
    working_dir: /telegram_scrapper
    command: >
      bash -c "
        source .env &&
        pip install -r requirements.txt &&
        python manage.py collectstatic --noinput &&
        gunicorn telegram_scrapper.wsgi -b :8000
      "
    ports:
      - 8002:8000
    environment:
      - DEBUG
      - DATABASE_URL
      - ALLOWED_HOSTS
      - SECRET_KEY
      - TELEGRAM_API_ID
      - TELEGRAM_API_HASH
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
      - AWS_S3_REGION_NAME
    volumes:
      - .:/telegram_scrapper
    restart: always
